"""PDF export helpers for Inventory and Catalog lists using reportlab."""
import io
import os

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, Flowable
)


def _brand_header(doc, brand_title):
    """Return flowable header block with logo + title (best-effort)."""
    from reportlab.platypus import Table as T
    logo_path = os.path.join("static", "logo.jpg")
    parts = []
    logo_cell = None
    if os.path.exists(logo_path):
        try:
            logo_cell = Image(logo_path, width=18 * mm, height=18 * mm, hAlign="LEFT")
        except Exception:
            logo_cell = None

    cell = []
    title = Paragraph(f"<b>{brand_title}</b>", ParagraphStyle(
        "brandTitle", fontName="Helvetica-Bold", fontSize=20, leading=24,
        textColor=colors.HexColor("#1e293b")
    ))
    sub = Paragraph("CRM · Export", ParagraphStyle(
        "brandSub", fontName="Helvetica", fontSize=10, leading=13,
        textColor=colors.HexColor("#64748b")
    ))
    cell.append(title)
    cell.append(sub)

    data_row = []
    if logo_cell is not None:
        data_row.append([logo_cell, cell])
        widths = [22 * mm, None]
    else:
        data_row.append([cell])
        widths = [None]

    t = T(data_row, colWidths=widths)
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ]))
    parts.append(t)
    parts.append(Spacer(1, 6 * mm))
    parts.append(_hr())
    parts.append(Spacer(1, 4 * mm))
    return parts


def _hr():
    from reportlab.platypus import HRFlowable
    return HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"))


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#94a3b8"))
    canvas.drawString(10 * mm, 8 * mm, "Generated by SERP Hawk CRM")
    canvas.drawRightString(A4[0] - 10 * mm, 8 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _build_pdf(title, headers, rows, widths):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        leftMargin=12 * mm, rightMargin=12 * mm,
        topMargin=12 * mm, bottomMargin=14 * mm,
    )
    styles = getSampleStyleSheet()

    story = _brand_header(doc, title)

    header_style = ParagraphStyle(
        "hdr", parent=styles["Heading2"], fontSize=15, leading=19,
        textColor=colors.HexColor("#0f172a"), spaceBefore=2, spaceAfter=2
    )
    body_style = ParagraphStyle(
        "body", parent=styles["BodyText"], fontSize=8.5, leading=11,
        textColor=colors.HexColor("#334155"), spaceBefore=0, spaceAfter=0,
        wordWrap="CJK"
    )
    cell_style = ParagraphStyle(
        "cell", parent=body_style, alignment=TA_LEFT
    )

    story.append(Paragraph(title, header_style))
    story.append(Spacer(1, 3 * mm))

    table_data = [[Paragraph(f"<b>{h}</b>", ParagraphStyle(
        "th", parent=body_style, textColor=colors.white,
        fontName="Helvetica-Bold", alignment=TA_LEFT
    )) for h in headers]]
    for row in rows:
        cells = []
        for c in row:
            if isinstance(c, Flowable):
                cells.append(c)
            elif c is None:
                cells.append(Paragraph("", cell_style))
            else:
                cells.append(Paragraph(str(c), cell_style))
        table_data.append(cells)

    table = Table(table_data, colWidths=widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))

    story.append(table)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _resolve_image(src, width_mm, height_mm):
    """Return a reportlab Image flowable from a local path string, or None if unloadable."""
    if not src:
        return None
    path = src
    # /static/uploads/... -> static/uploads/...
    if path.startswith("/"):
        path = path.lstrip("/")
    if not os.path.exists(path):
        return None
    try:
        img = Image(path, width=width_mm, height=height_mm)
        img.hAlign = "CENTER"
        return img
    except Exception:
        return None


def _inventory_table(title, items):
    """Shared landscape table layout for inventory exports (full list & selected items)."""
    headers = ["Photo", "Code", "Name", "Category", "Stock", "Min Stock", "Unit", "Status", "Description"]
    widths = [16 * mm, 18 * mm, 30 * mm, 24 * mm, 15 * mm, 15 * mm, 14 * mm, 20 * mm, 48 * mm]

    rows = []
    for it in items:
        cur = it.get("current_stock") or 0
        mn = it.get("min_stock") or 0
        if cur <= 0:
            status = "Out of Stock"
        elif cur <= mn:
            status = "Low Stock"
        else:
            status = "In Stock"
        rows.append([
            _resolve_image(it.get("photo_url"), 15 * mm, 15 * mm),
            it.get("code") or "—",
            it.get("name") or "—",
            it.get("category") or "—",
            cur,
            mn,
            it.get("unit") or "—",
            status,
            it.get("description") or "",
        ])
    return _build_pdf(title, headers, rows, widths)


def inventory_pdf(items):
    """Generate a PDF of the inventory list (same structure as selected-item export)."""
    return _inventory_table("Inventory List", items)


def _item_card_story(it, doc):
    """Return a list of flowables rendering one inventory item card."""
    from reportlab.lib import colors as _colors
    from reportlab.lib.styles import getSampleStyleSheet as _gss, ParagraphStyle as _PS
    from reportlab.platypus import Paragraph as _P, Spacer as _Sp, Table as _T, TableStyle as _TS

    styles = _gss()
    story = []
    story.append(_P(f"<b>{it.get('name') or 'Inventory Item'}</b>", _PS(
        "itemTitle", parent=styles["Heading1"], fontSize=20, leading=24,
        textColor=_colors.HexColor("#0f172a"), spaceAfter=2)))
    story.append(_P(f"Code: {it.get('code') or '—'}", _PS(
        "itemCode", parent=styles["BodyText"], fontSize=11, textColor=_colors.HexColor("#64748b"), spaceAfter=8)))

    info = [
        ("Category", it.get("category") or "—"),
        ("Unit", it.get("unit") or "—"),
        ("Current Stock", it.get("current_stock") or 0),
        ("Min Stock", it.get("min_stock") or 0),
    ]
    rows = [[_P(f"<b>{k}</b>", _PS("lk", parent=styles["BodyText"], fontSize=10, textColor=_colors.HexColor("#475569"))),
             _P(str(v), _PS("lv", parent=styles["BodyText"], fontSize=10, textColor=_colors.HexColor("#0f172a")))]
            for k, v in info]
    info_table = _T(rows, colWidths=[40 * mm, 120 * mm])
    info_table.setStyle(_TS([
        ("BACKGROUND", (0, 0), (0, -1), _colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.4, _colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(info_table)
    if it.get("description"):
        story.append(_Sp(1, 6))
        from reportlab.lib.styles import ParagraphStyle as _PS2
        story.append(_P(f"<b>Description:</b> {it.get('description')}", _PS2(
            "desc", parent=styles["BodyText"], fontSize=10, textColor=_colors.HexColor("#334155"))))
    return story


def single_inventory_pdf(it, suppliers=None):
    """Generate a single inventory item card PDF."""
    import io as _io
    from reportlab.platypus import SimpleDocTemplate as _SDT

    buf = _io.BytesIO()
    doc = _SDT(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
               topMargin=15 * mm, bottomMargin=15 * mm)

    story = _brand_header(doc, "Inventory Item")
    story += _item_card_story(it, doc)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def multi_inventory_pdf(items):
    """Generate a PDF for multiple selected inventory items.

    Uses the exact same landscape table layout as the full inventory list and
    the product catalog, so every export keeps an identical structure.
    """
    return _inventory_table("Inventory Items", items)


def catalog_pdf(products, currency="MXN"):
    """Generate a PDF of the product catalog."""
    title = "Product Catalog"
    headers = ["Photo", "SKU", "Name", "Category", "Price", "Currency", "Tax %", "Stock", "Active", "Description"]
    widths = [16 * mm, 20 * mm, 34 * mm, 26 * mm, 16 * mm, 16 * mm, 13 * mm, 15 * mm, 14 * mm, 42 * mm]

    rows = []
    for p in products:
        rows.append([
            _resolve_image(p.get("photo_url"), 15 * mm, 15 * mm),
            p.get("sku") or "—",
            p.get("name") or "—",
            p.get("category") or "—",
            f"{p.get('unit_price', 0):,.2f}",
            p.get("currency") or currency,
            f"{p.get('tax_rate', 0)}",
            p.get("stock_quantity") if p.get("stock_quantity") is not None else "—",
            "Yes" if p.get("is_active") else "No",
            p.get("description") or "",
        ])
    return _build_pdf(title, headers, rows, widths)


def send_pdf_email(to_email, subject, body, pdf_bytes, filename):
    """Send a PDF attachment via the configured SMTP. Best-effort."""
    from modules.email_sender import send_email_outlook
    sender = os.environ.get("EMAIL_SENDER") or os.environ.get("OUTLOOK_EMAIL") or ""
    password = os.environ.get("EMAIL_PASSWORD") or os.environ.get("OUTLOOK_PASSWORD") or ""
    if not sender or not password:
        raise RuntimeError("SMTP not configured (missing EMAIL_SENDER/EMAIL_PASSWORD)")
    send_email_outlook(
        to_email=to_email,
        subject=subject,
        body=body,
        sender_email=sender,
        sender_password=password,
        attachments=[(filename, pdf_bytes, "application/pdf")],
    )


# ── Sales Order PDF helpers ──────────────────────────────────────────────

def sales_order_pdf(orders):
    """Generate a PDF table of all sales orders."""
    title = "Sales Orders"
    headers = ["Order #", "Client", "Amount", "Currency", "Status", "Delivery Date", "Created"]
    widths = [30 * mm, 40 * mm, 28 * mm, 20 * mm, 24 * mm, 30 * mm, 30 * mm]

    rows = []
    for o in orders:
        created = ""
        if o.get("created_at"):
            try:
                created = o["created_at"][:10]
            except Exception:
                created = str(o["created_at"])[:10]
        rows.append([
            o.get("order_number") or "—",
            o.get("client_name") or "—",
            f"{o.get('grand_total', 0):,.2f}",
            o.get("currency") or "USD",
            o.get("status") or "—",
            o.get("delivery_date") or "—",
            created,
        ])
    return _build_pdf(title, headers, rows, widths)


def _single_order_card_story(label, fields, doc):
    """Return flowables for a single order card (reused by sales & purchase)."""
    from reportlab.lib.styles import getSampleStyleSheet as _gss, ParagraphStyle as _PS
    from reportlab.platypus import Paragraph as _P, Spacer as _Sp, Table as _T, TableStyle as _TS

    styles = _gss()
    story = []

    title_style = _PS("orderTitle", parent=styles["Heading1"], fontSize=20, leading=24,
                       textColor=colors.HexColor("#0f172a"), spaceAfter=2)
    story.append(_P(f"<b>{label}</b>", title_style))

    rows = []
    for k, v in fields:
        key_p = _P(f"<b>{k}</b>", _PS("fk", parent=styles["BodyText"], fontSize=10,
                                       textColor=colors.HexColor("#475569")))
        val_p = _P(str(v) if v is not None else "—", _PS("fv", parent=styles["BodyText"],
                                                          fontSize=10, textColor=colors.HexColor("#0f172a")))
        rows.append([key_p, val_p])

    info_table = _T(rows, colWidths=[45 * mm, 120 * mm])
    info_table.setStyle(_TS([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(_Sp(1, 4 * mm))
    story.append(info_table)
    return story


def single_sales_order_pdf(order, client_name=None, lead_name=None):
    """Generate a single sales order PDF card."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=15 * mm, bottomMargin=15 * mm)

    party = client_name or lead_name or "—"
    created = ""
    if order.get("created_at"):
        try:
            created = order["created_at"][:10]
        except Exception:
            created = str(order["created_at"])[:10]

    fields = [
        ("Order Number", order.get("order_number") or "—"),
        ("Status", order.get("status") or "—"),
        ("Client / Lead", party),
        ("Grand Total", f"{order.get('currency', 'USD')} {order.get('grand_total', 0):,.2f}"),
        ("Delivery Date", order.get("delivery_date") or "—"),
        ("Notes", order.get("notes") or "—"),
        ("Created", created),
    ]
    story = _brand_header(doc, "Sales Order")
    story += _single_order_card_story(f"Sales Order — {order.get('order_number') or order.get('id', '')}", fields, doc)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


# ── Purchase Order PDF helpers ───────────────────────────────────────────

def purchase_order_pdf(orders):
    """Generate a PDF table of all purchase orders."""
    title = "Purchase Orders"
    headers = ["PO #", "Vendor", "Email", "Amount", "Currency", "Status", "Expected Delivery", "Created"]
    widths = [25 * mm, 32 * mm, 40 * mm, 24 * mm, 18 * mm, 22 * mm, 30 * mm, 28 * mm]

    rows = []
    for o in orders:
        created = ""
        if o.get("created_at"):
            try:
                created = o["created_at"][:10]
            except Exception:
                created = str(o["created_at"])[:10]
        rows.append([
            o.get("po_number") or "—",
            o.get("vendor_name") or "—",
            o.get("vendor_email") or "—",
            f"{o.get('grand_total', 0):,.2f}",
            o.get("currency") or "USD",
            o.get("status") or "—",
            o.get("expected_delivery") or "—",
            created,
        ])
    return _build_pdf(title, headers, rows, widths)


def single_purchase_order_pdf(order):
    """Generate a single purchase order PDF card."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=15 * mm, bottomMargin=15 * mm)

    created = ""
    if order.get("created_at"):
        try:
            created = order["created_at"][:10]
        except Exception:
            created = str(order["created_at"])[:10]

    fields = [
        ("PO Number", order.get("po_number") or "—"),
        ("Status", order.get("status") or "—"),
        ("Vendor Name", order.get("vendor_name") or "—"),
        ("Vendor Email", order.get("vendor_email") or "—"),
        ("Grand Total", f"{order.get('currency', 'USD')} {order.get('grand_total', 0):,.2f}"),
        ("Expected Delivery", order.get("expected_delivery") or "—"),
        ("Notes", order.get("notes") or "—"),
        ("Created", created),
    ]
    story = _brand_header(doc, "Purchase Order")
    story += _single_order_card_story(f"Purchase Order — {order.get('po_number') or order.get('id', '')}", fields, doc)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()