"""PDF export helpers for Inventory and Catalog lists using reportlab."""
import io
import os

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, Flowable, KeepTogether, HRFlowable
)


def _brand_header(doc, brand_title):
    """Return flowable header block with logo + title (best-effort)."""
    from reportlab.platypus import Table as T
    logo_path = os.path.join("static", "logo.jpg")
    parts = []
    logo_cell = None
    if os.path.exists(logo_path):
        try:
            logo_cell = Image(logo_path, width=18 * mm, height=18 * mm, hAlign="LEFT")
        except Exception:
            logo_cell = None

    cell = []
    title = Paragraph(f"<b>{brand_title}</b>", ParagraphStyle(
        "brandTitle", fontName="Helvetica-Bold", fontSize=20, leading=24,
        textColor=colors.HexColor("#1e293b")
    ))
    sub = Paragraph("CRM · Export", ParagraphStyle(
        "brandSub", fontName="Helvetica", fontSize=10, leading=13,
        textColor=colors.HexColor("#64748b")
    ))
    cell.append(title)
    cell.append(sub)

    data_row = []
    if logo_cell is not None:
        data_row.append([logo_cell, cell])
        widths = [22 * mm, None]
    else:
        data_row.append([cell])
        widths = [None]

    t = T(data_row, colWidths=widths)
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ]))
    parts.append(t)
    parts.append(Spacer(1, 6 * mm))
    parts.append(_hr())
    parts.append(Spacer(1, 4 * mm))
    return parts


def _hr():
    from reportlab.platypus import HRFlowable
    return HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"))


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#94a3b8"))
    canvas.drawString(10 * mm, 8 * mm, "Generated by SERP Hawk CRM")
    canvas.drawRightString(A4[0] - 10 * mm, 8 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _build_pdf(title, headers, rows, widths):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        leftMargin=12 * mm, rightMargin=12 * mm,
        topMargin=12 * mm, bottomMargin=14 * mm,
    )
    styles = getSampleStyleSheet()

    story = _brand_header(doc, title)

    header_style = ParagraphStyle(
        "hdr", parent=styles["Heading2"], fontSize=15, leading=19,
        textColor=colors.HexColor("#0f172a"), spaceBefore=2, spaceAfter=2
    )
    body_style = ParagraphStyle(
        "body", parent=styles["BodyText"], fontSize=8.5, leading=11,
        textColor=colors.HexColor("#334155"), spaceBefore=0, spaceAfter=0,
        wordWrap="CJK"
    )
    cell_style = ParagraphStyle(
        "cell", parent=body_style, alignment=TA_LEFT
    )

    story.append(Paragraph(title, header_style))
    story.append(Spacer(1, 3 * mm))

    table_data = [[Paragraph(f"<b>{h}</b>", ParagraphStyle(
        "th", parent=body_style, textColor=colors.white,
        fontName="Helvetica-Bold", alignment=TA_LEFT
    )) for h in headers]]
    for row in rows:
        cells = []
        for c in row:
            if isinstance(c, Flowable):
                cells.append(c)
            elif c is None:
                cells.append(Paragraph("", cell_style))
            else:
                cells.append(Paragraph(str(c), cell_style))
        table_data.append(cells)

    table = Table(table_data, colWidths=widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))

    story.append(table)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _resolve_image(src, width_mm, height_mm):
    """Return a reportlab Image flowable from a local path string, or None if unloadable."""
    if not src:
        return None
    path = src
    # /static/uploads/... -> static/uploads/...
    if path.startswith("/"):
        path = path.lstrip("/")
    if not os.path.exists(path):
        return None
    try:
        img = Image(path, width=width_mm, height=height_mm)
        img.hAlign = "CENTER"
        return img
    except Exception:
        return None


def _inventory_table(title, items):
    """A4 portrait inventory list styled on the minimal SERPHAWK template
    (the reference design): white background, dark text, gray secondary text,
    thin light-gray dividers, small product thumbnails, colored stock status."""
    from datetime import datetime

    headers = ["Photo", "Code", "Name", "Category", "Stock", "Min", "Unit", "Status", "Description"]
    widths = [14 * mm, 20 * mm, 40 * mm, 22 * mm, 14 * mm, 12 * mm, 13 * mm, 18 * mm, 27 * mm]

    data = []
    total_stock = 0
    low_count = 0
    out_count = 0
    for it in items:
        cur = it.get("current_stock") or 0
        mn = it.get("min_stock") or 0
        try:
            cur = float(cur)
        except (TypeError, ValueError):
            cur = 0
        try:
            mn = float(mn)
        except (TypeError, ValueError):
            mn = 0
        cur_int = int(cur)
        mn_int = int(mn)
        total_stock += cur_int
        if cur_int <= 0:
            status, kind = "Out of Stock", "bad"
            out_count += 1
        elif cur_int <= mn_int:
            status, kind = "Low Stock", "warn"
            low_count += 1
        else:
            status, kind = "In Stock", "ok"

        img = _receipt_image_flowable(it.get("photo_url"), 12 * mm) or _ImagePlaceholder(12 * mm, 12 * mm)
        photo_cell = Table([[img]], colWidths=[14 * mm])
        photo_cell.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))

        def c_txt(v, fs=8.5, color=_RECEIPT_INK, align=TA_LEFT):
            return Paragraph(str(v), ParagraphStyle(
                "ic", fontName="Helvetica", fontSize=fs, leading=11, textColor=color,
                alignment=align, spaceBefore=0, spaceAfter=0, wordWrap="CJK"))

        data.append([
            photo_cell,
            c_txt(it.get("code") or "—", color=_CATALOG_MUTED),
            c_txt(it.get("name") or "—", fs=9),
            c_txt(it.get("category") or "—", color=_RECEIPT_SUBTLE),
            c_txt(cur_int, align=TA_RIGHT),
            c_txt(mn_int, align=TA_RIGHT, color=_CATALOG_MUTED),
            c_txt(it.get("unit") or "—", color=_RECEIPT_SUBTLE),
            _status_para(status, kind),
            c_txt(it.get("description") or "", fs=7.5, color=_CATALOG_MUTED),
        ])

    summary = [
        ("Total Items", str(len(items))),
        ("Units in Stock", str(total_stock)),
        ("Low Stock", str(low_count)),
        ("Out of Stock", str(out_count)),
    ]
    return _catalog_table_template(title, headers, widths, data, summary=summary, footer_label="SERPHAWK · Inventario")


def inventory_pdf(items):
    """Generate a PDF of the inventory list (same structure as selected-item export)."""
    return _inventory_table("Inventory List", items)


def _item_card_story(it, doc):
    """Return a list of flowables rendering one inventory item card."""
    from reportlab.lib import colors as _colors
    from reportlab.lib.styles import getSampleStyleSheet as _gss, ParagraphStyle as _PS
    from reportlab.platypus import Paragraph as _P, Spacer as _Sp, Table as _T, TableStyle as _TS

    styles = _gss()
    story = []
    story.append(_P(f"<b>{it.get('name') or 'Inventory Item'}</b>", _PS(
        "itemTitle", parent=styles["Heading1"], fontSize=20, leading=24,
        textColor=_colors.HexColor("#0f172a"), spaceAfter=2)))
    story.append(_P(f"Code: {it.get('code') or '—'}", _PS(
        "itemCode", parent=styles["BodyText"], fontSize=11, textColor=_colors.HexColor("#64748b"), spaceAfter=8)))

    info = [
        ("Category", it.get("category") or "—"),
        ("Unit", it.get("unit") or "—"),
        ("Current Stock", it.get("current_stock") or 0),
        ("Min Stock", it.get("min_stock") or 0),
    ]
    rows = [[_P(f"<b>{k}</b>", _PS("lk", parent=styles["BodyText"], fontSize=10, textColor=_colors.HexColor("#475569"))),
             _P(str(v), _PS("lv", parent=styles["BodyText"], fontSize=10, textColor=_colors.HexColor("#0f172a")))]
            for k, v in info]
    info_table = _T(rows, colWidths=[40 * mm, 120 * mm])
    info_table.setStyle(_TS([
        ("BACKGROUND", (0, 0), (0, -1), _colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.4, _colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(info_table)
    if it.get("description"):
        story.append(_Sp(1, 6))
        from reportlab.lib.styles import ParagraphStyle as _PS2
        story.append(_P(f"<b>Description:</b> {it.get('description')}", _PS2(
            "desc", parent=styles["BodyText"], fontSize=10, textColor=_colors.HexColor("#334155"))))
    return story


def single_inventory_pdf(it, suppliers=None):
    """Generate a single inventory item card PDF."""
    import io as _io
    from reportlab.platypus import SimpleDocTemplate as _SDT

    buf = _io.BytesIO()
    doc = _SDT(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
               topMargin=15 * mm, bottomMargin=15 * mm)

    story = _brand_header(doc, "Inventory Item")
    story += _item_card_story(it, doc)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def multi_inventory_pdf(items):
    """Generate a PDF for multiple selected inventory items.

    Uses the exact same landscape table layout as the full inventory list and
    the product catalog, so every export keeps an identical structure.
    """
    return _inventory_table("Inventory Items", items)


def catalog_pdf(products, currency="MXN"):
    """Generate a polished A4 portrait PDF of the product catalog,
    matching the minimal SERPHAWK template used by the inventory export."""
    headers = ["Photo", "SKU", "Name", "Category", "Price", "Tax", "Stock", "Status", "Description"]
    widths = [14 * mm, 20 * mm, 38 * mm, 22 * mm, 18 * mm, 12 * mm, 14 * mm, 17 * mm, 25 * mm]
    currency = str(currency or "MXN")

    data = []
    total_value = 0.0
    for p in products:
        price = p.get("unit_price")
        try:
            price_f = float(price or 0)
        except (TypeError, ValueError):
            price_f = 0.0
        stock = p.get("stock_quantity")
        try:
            stock_f = float(stock or 0)
        except (TypeError, ValueError):
            stock_f = 0
        stock_int = int(stock_f)
        total_value += price_f * stock_f

        active = bool(p.get("is_active"))
        if not active:
            status, kind = "Inactive", "muted"
        elif stock_int <= 0:
            status, kind = "Out of Stock", "bad"
        elif stock_int <= 5:
            status, kind = "Low Stock", "warn"
        else:
            status, kind = "Active", "ok"

        img = _receipt_image_flowable(p.get("photo_url"), 12 * mm) or _ImagePlaceholder(12 * mm, 12 * mm)
        photo_cell = Table([[img]], colWidths=[14 * mm])
        photo_cell.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))

        def c_txt(v, fs=8.5, color=_RECEIPT_INK, align=TA_LEFT):
            return Paragraph(str(v), ParagraphStyle(
                "cc", fontName="Helvetica", fontSize=fs, leading=11, textColor=color,
                alignment=align, spaceBefore=0, spaceAfter=0, wordWrap="CJK"))

        tax = p.get("tax_rate")
        if tax is None or tax == "" or tax == 0:
            tax_txt = "—"
        else:
            tax_txt = f"{tax}%"

        data.append([
            photo_cell,
            c_txt(p.get("sku") or "—", color=_CATALOG_MUTED),
            c_txt(p.get("name") or "—", fs=9),
            c_txt(p.get("category") or "—", color=_RECEIPT_SUBTLE),
            c_txt(f"{price_f:,.2f} {_currency_symbol(currency)}", align=TA_RIGHT, fs=9),
            c_txt(tax_txt, color=_CATALOG_MUTED, align=TA_RIGHT),
            c_txt(stock_int, align=TA_RIGHT),
            _status_para(status, kind),
            c_txt(p.get("description") or "", fs=7.5, color=_CATALOG_MUTED),
        ])

    summary = [
        ("Products", str(len(products))),
        ("Items in Stock", str(int(sum(float(p.get("stock_quantity") or 0) for p in products)))),
        ("Catalog Value", f"{total_value:,.2f} {_currency_symbol(currency)}"),
    ]
    meta = [("Export:", "Product Catalog"), ("Currency:", str(currency).upper())]
    return _catalog_table_template("Product Catalog", headers, widths, data,
                                   meta_left=meta, summary=summary,
                                   footer_label="SERPHAWK · Catálogo de Productos")


def send_pdf_email(to_email, subject, body, pdf_bytes, filename):
    """Send a PDF attachment via the configured SMTP. Best-effort."""
    from modules.email_sender import send_email_outlook
    sender = os.environ.get("EMAIL_SENDER") or os.environ.get("OUTLOOK_EMAIL") or ""
    password = os.environ.get("EMAIL_PASSWORD") or os.environ.get("OUTLOOK_PASSWORD") or ""
    if not sender or not password:
        raise RuntimeError("SMTP not configured (missing EMAIL_SENDER/EMAIL_PASSWORD)")
    smtp_server = os.environ.get("EMAIL_HOST") or os.environ.get("SMTP_SERVER") or "mail.serphawk.in"
    smtp_port = int(os.environ.get("EMAIL_PORT") or os.environ.get("SMTP_PORT") or 587)
    send_email_outlook(
        to_email=to_email,
        subject=subject,
        body=body,
        sender_email=sender,
        sender_password=password,
        smtp_server=smtp_server,
        smtp_port=smtp_port,
        attachments=[(filename, pdf_bytes, "application/pdf")],
    )


# ── Sales Order PDF helpers ──────────────────────────────────────────────

def sales_order_pdf(orders):
    """Generate a PDF table of all sales orders."""
    title = "Sales Orders"
    headers = ["Order #", "Client", "Amount", "Currency", "Status", "Delivery Date", "Created"]
    widths = [30 * mm, 40 * mm, 28 * mm, 20 * mm, 24 * mm, 30 * mm, 30 * mm]

    rows = []
    for o in orders:
        created = ""
        if o.get("created_at"):
            try:
                created = o["created_at"][:10]
            except Exception:
                created = str(o["created_at"])[:10]
        rows.append([
            o.get("order_number") or "—",
            o.get("client_name") or "—",
            f"{o.get('grand_total', 0):,.2f}",
            o.get("currency") or "USD",
            o.get("status") or "—",
            o.get("delivery_date") or "—",
            created,
        ])
    return _build_pdf(title, headers, rows, widths)


def _single_order_card_story(label, fields, doc):
    """Return flowables for a single order card (reused by sales & purchase)."""
    from reportlab.lib.styles import getSampleStyleSheet as _gss, ParagraphStyle as _PS
    from reportlab.platypus import Paragraph as _P, Spacer as _Sp, Table as _T, TableStyle as _TS

    styles = _gss()
    story = []

    title_style = _PS("orderTitle", parent=styles["Heading1"], fontSize=20, leading=24,
                       textColor=colors.HexColor("#0f172a"), spaceAfter=2)
    story.append(_P(f"<b>{label}</b>", title_style))

    rows = []
    for k, v in fields:
        key_p = _P(f"<b>{k}</b>", _PS("fk", parent=styles["BodyText"], fontSize=10,
                                       textColor=colors.HexColor("#475569")))
        val_p = _P(str(v) if v is not None else "—", _PS("fv", parent=styles["BodyText"],
                                                          fontSize=10, textColor=colors.HexColor("#0f172a")))
        rows.append([key_p, val_p])

    info_table = _T(rows, colWidths=[45 * mm, 120 * mm])
    info_table.setStyle(_TS([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(_Sp(1, 4 * mm))
    story.append(info_table)
    return story


def single_sales_order_pdf(order, client_name=None, lead_name=None):
    """Generate a single sales order PDF card."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=15 * mm, bottomMargin=15 * mm)

    party = client_name or lead_name or "—"
    created = ""
    if order.get("created_at"):
        try:
            created = order["created_at"][:10]
        except Exception:
            created = str(order["created_at"])[:10]

    fields = [
        ("Order Number", order.get("order_number") or "—"),
        ("Status", order.get("status") or "—"),
        ("Client / Lead", party),
        ("Grand Total", f"{order.get('currency', 'USD')} {order.get('grand_total', 0):,.2f}"),
        ("Delivery Date", order.get("delivery_date") or "—"),
        ("Notes", order.get("notes") or "—"),
        ("Created", created),
    ]
    story = _brand_header(doc, "Sales Order")
    story += _single_order_card_story(f"Sales Order — {order.get('order_number') or order.get('id', '')}", fields, doc)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


# ── Purchase Order PDF helpers ───────────────────────────────────────────

def purchase_order_pdf(orders):
    """Generate a PDF table of all purchase orders."""
    title = "Purchase Orders"
    headers = ["PO #", "Vendor", "Email", "Amount", "Currency", "Status", "Expected Delivery", "Created"]
    widths = [25 * mm, 32 * mm, 40 * mm, 24 * mm, 18 * mm, 22 * mm, 30 * mm, 28 * mm]

    rows = []
    for o in orders:
        created = ""
        if o.get("created_at"):
            try:
                created = o["created_at"][:10]
            except Exception:
                created = str(o["created_at"])[:10]
        rows.append([
            o.get("po_number") or "—",
            o.get("vendor_name") or "—",
            o.get("vendor_email") or "—",
            f"{o.get('grand_total', 0):,.2f}",
            o.get("currency") or "USD",
            o.get("status") or "—",
            o.get("expected_delivery") or "—",
            created,
        ])
    return _build_pdf(title, headers, rows, widths)


def single_purchase_order_pdf(order):
    """Generate a single purchase order PDF card."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=15 * mm, bottomMargin=15 * mm)

    created = ""
    if order.get("created_at"):
        try:
            created = order["created_at"][:10]
        except Exception:
            created = str(order["created_at"])[:10]

    fields = [
        ("PO Number", order.get("po_number") or "—"),
        ("Status", order.get("status") or "—"),
        ("Vendor Name", order.get("vendor_name") or "—"),
        ("Vendor Email", order.get("vendor_email") or "—"),
        ("Grand Total", f"{order.get('currency', 'USD')} {order.get('grand_total', 0):,.2f}"),
        ("Expected Delivery", order.get("expected_delivery") or "—"),
        ("Notes", order.get("notes") or "—"),
        ("Created", created),
    ]
    story = _brand_header(doc, "Purchase Order")
    story += _single_order_card_story(f"Purchase Order — {order.get('po_number') or order.get('id', '')}", fields, doc)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


# ── POS Receipt / Invoice PDF (A4 portrait) ───────────────────────────────

_RECEIPT_INK = colors.HexColor("#0f172a")      # near-black body text
_RECEIPT_SUBTLE = colors.HexColor("#64748b")   # muted labels
_RECEIPT_FAINT = colors.HexColor("#94a3b8")    # faint detail text
_RECEIPT_LINE = colors.HexColor("#e2e8f0")     # thin light-gray dividers

_CURRENCY_SYMBOLS = {
    "USD": "$", "MXN": "$", "COP": "$", "BRL": "R$", "EUR": "€",
    "GBP": "£", "INR": "₹", "PEN": "S/", "ARS": "$", "CLP": "$",
}


def _currency_symbol(currency):
    """Map a currency code to its symbol; anything else is used literally."""
    if not currency:
        return "$"
    symbol = _CURRENCY_SYMBOLS.get(str(currency).upper())
    return symbol if symbol is not None else str(currency)


def _receipt_money(value, currency):
    """Format a monetary value, e.g. 149.94 -> '$149.94'."""
    try:
        return f"{_currency_symbol(currency)}{float(value):,.2f}"
    except (TypeError, ValueError):
        return f"{_currency_symbol(currency)}0.00"


class _ImagePlaceholder(Flowable):
    """Small light-gray placeholder shown when a product has no usable image."""

    def __init__(self, width, height):
        super().__init__()
        self.width = width
        self.height = height

    def draw(self):
        c = self.canv
        c.saveState()
        c.setFillColor(colors.HexColor("#f1f5f9"))
        c.roundRect(0, 0, self.width, self.height, self.width * 0.12, fill=1, stroke=0)
        c.setFillColor(colors.HexColor("#cbd5e1"))
        # simple "photo" glyph: sky + mountain + sun
        c.circle(self.width * 0.76, self.height * 0.66, self.width * 0.09, fill=1, stroke=0)
        c.rect(self.width * 0.22, self.height * 0.18, self.width * 0.56, self.height * 0.30, fill=1, stroke=0)
        p = c.beginPath()
        p.moveTo(self.width * 0.22, self.height * 0.48)
        p.lineTo(self.width * 0.40, self.height * 0.70)
        p.lineTo(self.width * 0.52, self.height * 0.56)
        p.lineTo(self.width * 0.62, self.height * 0.64)
        p.lineTo(self.width * 0.78, self.height * 0.48)
        p.lineTo(self.width * 0.78, self.height * 0.22)
        p.close()
        c.drawPath(p, fill=1, stroke=0)
        c.restoreState()


def _receipt_image_flowable(src, box=12 * mm):
    """Fit a product image inside a square box without distortion."""
    if not src:
        return None
    path = str(src).lstrip("/")
    if not os.path.exists(path):
        return None
    try:
        from reportlab.lib.utils import ImageReader
        reader = ImageReader(path)
        iw, ih = reader.getSize()
        if iw <= 0 or ih <= 0:
            return None
        scale = min(box / float(iw), box / float(ih))
        img = Image(path, width=float(iw) * scale, height=float(ih) * scale)
        img.hAlign = "LEFT"
        return img
    except Exception:
        return None


_CATALOG_OK = colors.HexColor("#059669")     # in stock / active
_CATALOG_WARN = colors.HexColor("#d97706")   # low stock
_CATALOG_BAD = colors.HexColor("#dc2626")    # out of stock / inactive
_CATALOG_MUTED = colors.HexColor("#94a3b8")  # neutral status


def _status_para(text, kind, font_size=8.5, ls=11):
    """Return a colored status Paragraph (no filled pill, minimal template)."""
    color = {
        "ok": _CATALOG_OK, "warn": _CATALOG_WARN, "bad": _CATALOG_BAD, "muted": _CATALOG_MUTED,
    }.get(kind, _CATALOG_MUTED)
    return Paragraph(str(text), ParagraphStyle(
        "st", fontName="Helvetica-Bold", fontSize=font_size, leading=ls,
        textColor=color, alignment=TA_LEFT, spaceBefore=0, spaceAfter=0, wordWrap="CJK"))


def _catalog_table_template(title, headers, widths, data, meta_left=None, summary=None, footer_label=None):
    """Render a polished A4-portrait SERPHAWK table document.

    Shared by inventory list and product catalog so both exports look identical:
    minimal brand header, gray text labels, thin dividers, zebra-free rows,
    colored statuses and a compact page footer.
    """
    from datetime import datetime

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=14 * mm, bottomMargin=16 * mm,
        title=title, author="SERPHAWK",
    )

    def cell(fs=9, ls=12, color=_RECEIPT_INK, align=TA_LEFT, bold=False, wrap=True):
        return ParagraphStyle(
            "cc", fontName="Helvetica-Bold" if bold else "Helvetica",
            fontSize=fs, leading=ls, textColor=color, alignment=align,
            spaceBefore=0, spaceAfter=0, wordWrap="CJK" if wrap else None,
        )

    meta_lines = [("Date:", _english_datetime(datetime.now())), ("Records:", str(len(data)))]
    if meta_left:
        meta_lines = meta_left + meta_lines

    story = []
    story += _serphawk_header(
        "SERPHAWK", meta_lines, subtitle=title,
    )

    table_data = [[Paragraph(h, cell(7.5, 10, _CATALOG_MUTED, align=TA_LEFT, bold=True)) for h in headers]]
    for row in data:
        table_data.append([
            c if isinstance(c, Flowable) else (Paragraph(str(c), cell(8.5, 11, _RECEIPT_INK, align=TA_LEFT)) if not isinstance(c, Paragraph) else c)
            for c in row
        ])

    style = [
        ("VALIGN", (0, 0), (-1, 0), "BOTTOM"),
        ("VALIGN", (0, 1), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, 0), 0),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 4),
        ("TOPPADDING", (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, 0), 0.6, _RECEIPT_LINE),
    ]
    for idx in range(1, len(table_data)):
        style.append(("LINEBELOW", (0, idx), (-1, idx), 0.4, colors.HexColor("#eef2f7")))

    table = Table(table_data, colWidths=widths, repeatRows=1)
    table.setStyle(TableStyle(style))
    story.append(table)

    # Summary band (e.g. total items / total value)
    if summary:
        story.append(Spacer(1, 5 * mm))
        summary_rows = [[
            Paragraph(k, cell(8, 10, _CATALOG_MUTED, align=TA_RIGHT, bold=True)),
            Paragraph(v, cell(9, 12, _RECEIPT_INK, align=TA_RIGHT, bold=True)),
        ] for k, v in summary]
        st = Table(summary_rows, colWidths=[120 * mm, 60 * mm])
        st.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LINEABOVE", (0, 0), (-1, -1), 0.6, _RECEIPT_LINE),
        ]))
        story.append(KeepTogether([st]))

    def _inventory_footer(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(_CATALOG_MUTED)
        canvas.drawString(15 * mm, 9 * mm, (footer_label or title))
        canvas.drawRightString(A4[0] - 15 * mm, 9 * mm, f"Página {_doc.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_inventory_footer, onLaterPages=_inventory_footer)
    return buf.getvalue()


_MESES_ES = [
    "enero", "febrero", "marzo", "abril", "mayo", "junio",
    "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre",
]


def _spanish_datetime(dt):
    """Format a datetime like the reference receipt, e.g.
    '6 de julio de 2026 a las 11:02:23 p.m.'"""
    if dt is None:
        return ""
    return (
        f"{dt.day} de {_MESES_ES[dt.month - 1]} de {dt.year} "
        f"a las {dt.strftime('%I:%M:%S')} {dt.strftime('%p').lower()}"
    )


def _english_datetime(dt):
    """Format a datetime in English, e.g. 'Sep 10, 2026 at 4:38 PM'."""
    if dt is None:
        return ""
    return dt.strftime("%b %d, %Y at %I:%M %p").replace(" 0", " ")


def _serphawk_header(title_text, meta_lines=None, subtitle=None):
    """Shared minimal SERPHAWK document header (reference-template).

    Bold brand at the top-left, small metadata block at the top-right, then a
    thin light-gray divider. Every document built on this template (receipt,
    inventory list, ...) shares the exact same typography / spacing / margins.

    ``meta_lines`` is a list of ``(label, value)`` tuples rendered right-aligned
    with bold labels and normal-weight values, e.g. ("Ticket:", "#2").
    """
    from reportlab.platypus import HRFlowable as _HR

    left_parts = [Paragraph(title_text, ParagraphStyle(
        "shBrand", fontName="Helvetica-Bold", fontSize=16, leading=19,
        textColor=_RECEIPT_INK, wordWrap="CJK"))]
    if subtitle:
        left_parts.append(Paragraph(subtitle, ParagraphStyle(
            "shSub", fontName="Helvetica", fontSize=9.5, leading=12,
            textColor=_RECEIPT_SUBTLE, wordWrap="CJK", spaceBefore=2)))

    right_cell = None
    if meta_lines:
        meta_paras = [
            Paragraph(f"<b>{label}</b> {value}", ParagraphStyle(
                "shMeta", fontName="Helvetica", fontSize=9, leading=12,
                textColor=_RECEIPT_INK, alignment=TA_RIGHT, wordWrap="CJK"))
            for label, value in meta_lines
        ]
        right_cell = Table([[p] for p in meta_paras], colWidths=[None])
        right_cell.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 1.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))

    left_cell = Table([[p] for p in left_parts], colWidths=[None])
    left_cell.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))

    if right_cell is not None:
        header_table = Table([[left_cell, right_cell]], colWidths=[100 * mm, 80 * mm])
    else:
        header_table = Table([[left_cell]], colWidths=[180 * mm])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    flow = [header_table, Spacer(1, 5 * mm)]
    flow.append(_HR(width="100%", thickness=0.6, color=_RECEIPT_LINE, spaceBefore=0, spaceAfter=0))
    flow.append(Spacer(1, 5 * mm))
    return flow


def pos_receipt_pdf(data):
    """Generate a clean, minimal A4 portrait POS receipt / invoice in Spanish.

    Accepted payload (all keys optional, calculations are automatic):

        companyName  : store name, defaults to "SERPHAWK"
        ticketNumber : e.g. 2  -> displayed as "Ticket: #2"
        date         : display string, e.g. "6 de julio de 2026 a las 11:02:23 p.m."
        customer     : defaults to "Público en General"
        products     : [ { name, image, quantity, unitPrice, subtotal } ]
        subtotal     : overall subtotal (falls back to sum of line items)
        taxRate      : e.g. 16 (percent). Default 0.
        taxAmount    : explicit tax amount (computed if omitted)
        total        : explicit total (computed if omitted)
        paymentMethod: e.g. "Efectivo"
        amountPaid   : money handed over (defaults to total)
        change       : change due (computed as amountPaid - total)
        currency     : currency code or literal symbol, defaults to "$"
        taxLabel     : label prefix, defaults to "IVA"
        taxIncluded  : True  -> tax is inside the total (Total == Subtotal),
                       False -> tax is added on top (Total = Subtotal + tax)

    Returns raw PDF bytes.
    """
    company_name = str(data.get("companyName") or "SERPHAWK")
    ticket = data.get("ticketNumber")
    ticket_str = f"#{ticket}" if ticket is not None and str(ticket) != "" else ""
    date_str = str(data.get("date") or "")
    customer = str(data.get("customer") or "Público en General")
    currency = data.get("currency") or "$"
    tax_rate = data.get("taxRate") or 0
    try:
        tax_rate = float(tax_rate)
    except (TypeError, ValueError):
        tax_rate = 0
    tax_included = bool(data.get("taxIncluded", True))
    tax_label = str(data.get("taxLabel") or "IVA")

    # 1/3 line totals + money
    products = data.get("products") or []
    line_rows = []
    subtotal = 0.0
    for p in products:
        qty = float(p.get("quantity") or 0)
        unit = float(p.get("unitPrice") or 0)
        line_total = round(qty * unit, 2)
        if p.get("subtotal") is not None:
            try:
                line_total = round(float(p["subtotal"]), 2)
            except (TypeError, ValueError):
                pass
        subtotal += line_total
        line_rows.append({
            "name": str(p.get("name") or "Producto"),
            "image": p.get("image"),
            "quantity": qty,
            "unit_price": unit,
            "subtotal": line_total,
        })
    subtotal = round(subtotal, 2)

    tax_amount = data.get("taxAmount")
    if tax_amount is None:
        if tax_included and tax_rate > 0:
            tax_amount = round(subtotal - subtotal / (1 + tax_rate / 100.0), 2)
        else:
            tax_amount = round(subtotal * tax_rate / 100.0, 2)
    tax_amount = round(float(tax_amount or 0), 2)

    total = data.get("total")
    if total is None:
        total = subtotal if tax_included else round(subtotal + tax_amount, 2)
    total = round(float(total or 0), 2)

    amount_paid = data.get("amountPaid")
    if amount_paid is None:
        amount_paid = total
    amount_paid = round(float(amount_paid or 0), 2)
    change = round(amount_paid - total, 2)
    payment = str(data.get("paymentMethod") or "Efectivo")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=14 * mm, bottomMargin=16 * mm,
        title=f"{company_name} — Ticket {ticket_str}",
        author=company_name,
    )

    def base(font_size=9, leading=12, color=_RECEIPT_INK, align=TA_LEFT, bold=False, wrap=True):
        return ParagraphStyle(
            "r", fontName="Helvetica-Bold" if bold else "Helvetica",
            fontSize=font_size, leading=leading, textColor=color,
            alignment=align, spaceBefore=0, spaceAfter=0, wordWrap="CJK" if wrap else None,
        )

    # ── Header ───────────────────────────────────────────────────────────
    meta_lines = []
    if ticket_str:
        meta_lines.append(("Ticket:", ticket_str))
    if date_str:
        meta_lines.append(("Fecha:", date_str))
    meta_lines.append(("Cliente:", customer))
    story = _serphawk_header(company_name, meta_lines if meta_lines else None)

    # ── Product table ────────────────────────────────────────────────────
    w_product, w_qty, w_price, w_sub = 90 * mm, 27 * mm, 36 * mm, 27 * mm

    def header_cell(text):
        return Paragraph(text, base(7.5, 10, _RECEIPT_SUBTLE, TA_LEFT, bold=True))

    table_data = [[
        header_cell("Producto"),
        header_cell("Cantidad"),
        header_cell("Precio Unitario"),
        header_cell("Subtotal"),
    ]]

    name_col = ParagraphStyle("rname", parent=base(9, 12, _RECEIPT_INK), wordWrap="CJK")

    for idx, row in enumerate(line_rows):
        img = _receipt_image_flowable(row["image"], 12 * mm) or _ImagePlaceholder(12 * mm, 12 * mm)
        name_para = Paragraph(row["name"], name_col)
        name_cell = Table([[img, name_para]], colWidths=[12 * mm, w_product - 12 * mm - 4])
        name_cell.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (0, 0), "LEFT"),
            ("ALIGN", (1, 0), (1, 0), "LEFT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))

        qty = row["quantity"]
        qty_text = f"{qty:g} {'unidad' if qty == 1 else 'unidades'}"
        table_data.append([
            name_cell,
            Paragraph(qty_text, base(9, 12, _RECEIPT_INK, TA_LEFT)),
            Paragraph(_receipt_money(row["unit_price"], currency), base(9, 12, _RECEIPT_INK, TA_RIGHT)),
            Paragraph(_receipt_money(row["subtotal"], currency), base(9, 12, _RECEIPT_INK, TA_RIGHT)),
        ])

    item_style = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, 0), "LEFT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]
    if line_rows:
        # light dividers between the table sections (header skim line + each row)
        item_style.append(("LINEBELOW", (0, 0), (-1, 0), 0.6, _RECEIPT_LINE))
        for idx in range(1, len(table_data)):
            item_style.append(("LINEBELOW", (0, idx), (-1, idx), 0.5, _RECEIPT_LINE))
        item_style.append(("BOTTOMPADDING", (0, 1), (-1, -1), 5))
        item_style.append(("TOPPADDING", (0, 1), (-1, -1), 5))

    items_table = Table(table_data, colWidths=[w_product, w_qty, w_price, w_sub], repeatRows=1)
    items_table.setStyle(TableStyle(item_style))
    story.append(items_table)
    story.append(Spacer(1, 8 * mm))

    # ── Totals + payment block (kept together, right-aligned) ────────────
    money_right = base(9, 12, _RECEIPT_INK, TA_RIGHT)
    label_right = base(9, 12, _RECEIPT_INK, TA_RIGHT)

    totals = [
        [Paragraph("Subtotal", label_right), Paragraph(_receipt_money(subtotal, currency), money_right)],
    ]
    totals.append([
        Paragraph("Total", base(10, 13, _RECEIPT_INK, TA_RIGHT, bold=True)),
        Paragraph(_receipt_money(total, currency), base(10, 13, _RECEIPT_INK, TA_RIGHT, bold=True)),
    ])
    if tax_rate > 0:
        totals.append([
            Paragraph(f"{tax_label} {tax_rate:g}% Incluido", base(8, 11, _RECEIPT_FAINT, TA_RIGHT)),
            Paragraph(_receipt_money(tax_amount, currency), base(8, 11, _RECEIPT_FAINT, TA_RIGHT)),
        ])
    totals.append([
        Paragraph("Pago", base(8.5, 11, _RECEIPT_SUBTLE, TA_RIGHT, bold=True)),
        Paragraph("", base(8.5, 11)),
    ])
    totals.append([
        Paragraph(payment, label_right),
        Paragraph(_receipt_money(amount_paid, currency), money_right),
    ])
    totals.append([
        Paragraph("Cambio", label_right),
        Paragraph(_receipt_money(change, currency), money_right),
    ])

    totals_table = Table(totals, colWidths=[64 * mm, 56 * mm], hAlign="RIGHT")
    totals_style = [
        ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LINEABOVE", (0, 1), (-1, 1), 0.6, _RECEIPT_LINE),
        ("LINEBELOW", (0, 1), (-1, 1), 0.6, _RECEIPT_LINE),
        ("TOPPADDING", (0, 1), (-1, 1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 5),
    ]
    if tax_rate > 0:
        totals_style.append(("LINEABOVE", (0, 2), (-1, 2), 0.6, _RECEIPT_LINE))
        totals_style.append(("LINEBELOW", (0, 2), (-1, 2), 0.6, _RECEIPT_LINE))
        totals_style.append(("TOPPADDING", (0, 2), (-1, 2), 4))
        totals_style.append(("BOTTOMPADDING", (0, 2), (-1, 2), 4))
    totals_table.setStyle(TableStyle(totals_style))

    story.append(KeepTogether([totals_table]))

    # ── Footer (only appears when the receipt spans multiple pages) ──────
    def _receipt_footer(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(_RECEIPT_FAINT)
        canvas.drawRightString(A4[0] - 15 * mm, 9 * mm, f"Ticket {ticket_str} · Página {_doc.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=lambda c, d: None, onLaterPages=_receipt_footer)
    return buf.getvalue()


def _q_section_title(text):
    return Paragraph(text, ParagraphStyle(
        "qsec", fontName="Helvetica-Bold", fontSize=9, leading=12,
        textColor=_RECEIPT_INK, spaceBefore=0, spaceAfter=0))


class _QuoteCanvas:
    """Canvas subclass that adds 'Page X of Y' footer.

    First layout pass fills ``_saved_page_states`` without finalizing pages.
    On ``save()``, each page state is replayed with the footer drawn before
    the page is flushed to the PDF.
    """
    def __init__(self, *args, **kwargs):
        from reportlab.pdfgen.canvas import Canvas
        self._canvas = Canvas(*args, **kwargs)
        self._saved_page_states = []

    def __getattr__(self, name):
        return getattr(self._canvas, name)

    def __setattr__(self, name, value):
        if name.startswith("_"):
            self.__dict__[name] = value
        else:
            setattr(self._canvas, name, value)

    def showPage(self):
        self._saved_page_states.append(dict(self._canvas.__dict__))
        self._canvas._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for i, state in enumerate(self._saved_page_states, 1):
            self._canvas.__dict__.update(state)
            self._draw_footer(i, total)
            self._canvas.showPage()
        self._canvas.save()

    def _draw_footer(self, page_num, total_pages):
        c = self._canvas
        c.saveState()
        c.setStrokeColor(_RECEIPT_LINE)
        c.setLineWidth(0.4)
        c.line(15 * mm, 14 * mm, A4[0] - 15 * mm, 14 * mm)
        c.setFont("Helvetica", 7.5)
        c.setFillColor(_RECEIPT_FAINT)
        c.drawString(15 * mm, 9 * mm, "SERPHAWK  ·  Professional Business Solutions")
        c.setFont("Helvetica", 8)
        c.drawRightString(A4[0] - 15 * mm, 9 * mm, f"Page {page_num} of {total_pages}")
        c.restoreState()


def quote_pdf(data):
    """Generate a SERPHAWK-minimal quote/proforma PDF (A4 portrait).

    ``data`` is a dict with keys:
        quote_number, title, status, client_name,
        client_company, client_email, client_phone, client_address,
        currency (default "$"), items (list), subtotal, tax_rate,
        discount, grand_total, valid_until, created_at,
        notes, terms, payment_terms, delivery
    """
    from datetime import datetime as _dt

    company = "SERPHAWK"
    currency = str(data.get("currency") or "$")
    subtitle = "Proforma Quotation"
    qn = data.get("quote_number") or str(data.get("id") or "")
    created = data.get("created_at") or ""
    if hasattr(created, "strftime"):
        created = _spanish_datetime(created)
    elif not isinstance(created, str) or not created:
        created = _spanish_datetime(_dt.now())

    def cell(fs=9, ls=12, color=_RECEIPT_INK, align=TA_LEFT, bold=False, wrap=True):
        return ParagraphStyle(
            "qp", fontName="Helvetica-Bold" if bold else "Helvetica",
            fontSize=fs, leading=ls, textColor=color, alignment=align,
            spaceBefore=0, spaceAfter=0, wordWrap="CJK" if wrap else None,
        )

    def P(text, style):
        return Paragraph(str(text or "") if text is not None else "", style)

    items = data.get("items") or []

    # ── Build doc ────────────────────────────────────────────────────────
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=16 * mm, bottomMargin=20 * mm,
        title=f"{company} — Quote {qn}",
        author=company,
    )

    story = []

    # ── 1) Header ────────────────────────────────────────────────────────
    left_parts = [
        Paragraph("SERPHAWK", ParagraphStyle(
            "qBrand", fontName="Helvetica-Bold", fontSize=17, leading=20,
            textColor=_RECEIPT_INK, wordWrap="CJK")),
        Paragraph(subtitle, ParagraphStyle(
            "qSub", fontName="Helvetica", fontSize=9.5, leading=12,
            textColor=_RECEIPT_SUBTLE, wordWrap="CJK", spaceBefore=3)),
    ]
    left_cell = Table([[p] for p in left_parts], colWidths=[None])
    left_cell.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))

    meta_paras = []
    if qn:
        meta_paras.append(P(f"<b fontName=\"Helvetica-Bold\">Quote:</b>&nbsp;&nbsp;#{qn}",
                            ParagraphStyle("qm0", fontSize=12, leading=15, textColor=_RECEIPT_INK, alignment=TA_RIGHT, wordWrap="CJK")))
    other_meta = []
    if created:
        other_meta.append(("Date", str(created)))
    if data.get("valid_until"):
        other_meta.append(("Valid Until", str(data["valid_until"])))
    if data.get("client_name"):
        other_meta.append(("For", data["client_name"]))
    for label, value in other_meta:
        meta_paras.append(P(f"<b>{label}</b>&nbsp;&nbsp;{value}",
                            ParagraphStyle("qm1", fontSize=8.5, leading=12,
                                           textColor=_RECEIPT_FAINT, alignment=TA_RIGHT, wordWrap="CJK")))
    if meta_paras:
        right_cell = Table([[p] for p in meta_paras], colWidths=[None])
        meta_style = [
            ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]
        for mi in range(len(meta_paras)):
            meta_style.append(("TOPPADDING", (0, mi), (0, mi), 6 if mi else 2))
        right_cell.setStyle(TableStyle(meta_style))
        header_table = Table([[left_cell, right_cell]], colWidths=[100 * mm, 80 * mm])
    else:
        header_table = Table([[left_cell]], colWidths=[180 * mm])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 5 * mm))
    story.append(HRFlowable(width="100%", thickness=0.6, color=_RECEIPT_LINE, spaceBefore=0, spaceAfter=0))
    story.append(Spacer(1, 6 * mm))

    # ── 2) BILL TO + status ──────────────────────────────────────────────
    bill_lines = []
    handle = data.get("client_name") or data.get("client_company")
    status = (data.get("status") or "").strip()
    title = (data.get("title") or "").strip()

    if handle:
        bill_lines.append(P(handle, ParagraphStyle("qb0", fontSize=11, leading=14, textColor=_RECEIPT_INK, wordWrap="CJK")))
    for label, value in [("Company", data.get("client_company")),
                         ("Email", data.get("client_email")),
                         ("Phone", data.get("client_phone")),
                         ("Address", data.get("client_address"))]:
        if value:
            bill_lines.append(P(f"<b>{label}:</b> {value}",
                                ParagraphStyle("qb1", fontSize=8.5, leading=12, textColor=_RECEIPT_SUBTLE, wordWrap="CJK")))
    if bill_lines:
        bill_table = Table([[Paragraph("BILL TO", ParagraphStyle(
            "qbt", fontName="Helvetica-Bold", fontSize=7.5, leading=9,
            textColor=_RECEIPT_FAINT, wordWrap="CJK"))]], colWidths=[100 * mm])
        bill_table.setStyle(TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ]))
        info_cell = Table([[p] for p in bill_lines], colWidths=[None])
        info_cell.setStyle(TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 1.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))

        sub_paras = []
        if status:
            sub_paras.append(Paragraph(status.upper(), ParagraphStyle(
                "qbadge", fontName="Helvetica-Bold", fontSize=7.5, leading=10,
                textColor=_RECEIPT_SUBTLE, alignment=TA_RIGHT,
                backColor=colors.HexColor("#f1f5f9"), borderPadding=(3, 8, 3, 8),
                wordWrap="CJK")))
        if title:
            sub_paras.append(P(f"<b>Title:</b> {title}",
                               ParagraphStyle("qbtitle", fontSize=8.5, leading=12,
                                              textColor=_RECEIPT_SUBTLE, alignment=TA_RIGHT, wordWrap="CJK")))
        right2 = None
        if sub_paras:
            right2 = Table([[p] for p in sub_paras], colWidths=[None])
            r2_style = [
                ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
            for ri in range(len(sub_paras)):
                r2_style.append(("TOPPADDING", (0, ri), (0, ri), 3 if ri else 0))
            right2.setStyle(TableStyle(r2_style))

        left_bundle = Table([[bill_table], [info_cell]], colWidths=[100 * mm])
        left_bundle.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))
        if right2 is not None:
            bill_wide = Table([[left_bundle, right2]], colWidths=[100 * mm, 80 * mm])
        else:
            bill_wide = Table([[left_bundle]], colWidths=[180 * mm])
        bill_wide.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))
        story.append(KeepTogether([bill_wide]))
        story.append(Spacer(1, 4 * mm))
        story.append(HRFlowable(width="100%", thickness=0.4, color=_RECEIPT_LINE, spaceBefore=0, spaceAfter=0))
        story.append(Spacer(1, 6 * mm))

    # ── 3) Line items table ──────────────────────────────────────────────
    headers = ["#", "Description", "Total"]
    col_w = [12 * mm, 128 * mm, 40 * mm]
    data_rows = [
        [Paragraph(h, ParagraphStyle(
            "qh", fontName="Helvetica-Bold", fontSize=8, leading=10,
            textColor=_RECEIPT_SUBTLE,
            alignment=(TA_CENTER if h in ("#",) else (TA_RIGHT if h in ("Total",) else TA_LEFT)),
            wordWrap="CJK")) for h in headers]
    ]
    for idx, li in enumerate(items, 1):
        qty = li.get("quantity") or 1
        up = float(li.get("unit_price") or 0)
        tot = float(li.get("total") or (up * qty))
        desc = str(li.get("description") or "")
        desc_html = desc
        subdesc = str(li.get("subdescription") or (li.get("name") or ""))
        if subdesc and subdesc != desc:
            desc_html = f"{desc} <font color=\"#94a3b8\" size=\"7.5\">{subdesc}</font>" if desc else subdesc
        data_rows.append([
            Paragraph(str(idx), cell(8.5, 13, _RECEIPT_FAINT, TA_CENTER)),
            Paragraph(desc_html, cell(9, 13, _RECEIPT_INK, TA_LEFT)),
            Paragraph(_receipt_money(tot, currency), cell(8.5, 13, _RECEIPT_INK, TA_RIGHT)),
        ])

    if not items:
        data_rows.append([
            Paragraph("", cell(9, 12, _RECEIPT_FAINT, TA_CENTER)),
            Paragraph("No items have been added to this quotation yet.", cell(9, 12, _RECEIPT_FAINT)),
            Paragraph("", cell(9, 12, _RECEIPT_FAINT)),
        ])

    item_style = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, 0), 2),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 4),
        ("TOPPADDING", (0, 1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, 0), 0.8, _RECEIPT_LINE),
    ]
    for idx in range(1, len(data_rows)):
        item_style.append(("LINEBELOW", (0, idx), (-1, idx), 0.4, colors.HexColor("#eef2f7")))
    items_table = Table(data_rows, colWidths=col_w, repeatRows=1)
    items_table.setStyle(TableStyle(item_style))
    story.append(KeepTogether([items_table]))

    # ── 4) Totals ────────────────────────────────────────────────────────
    subtotal = data.get("subtotal")
    tax_rate = data.get("tax_rate") or 0
    try:
        tax_rate = float(tax_rate)
    except Exception:
        tax_rate = 0
    discount = data.get("discount")
    try:
        discount = float(discount) if discount is not None else 0.0
    except Exception:
        discount = 0.0
    grand_total = data.get("grand_total")

    if subtotal is None:
        subtotal = sum(
            float(li.get("total") or (float(li.get("unit_price") or 0) * (li.get("quantity") or 1)))
            for li in items
        )
    else:
        subtotal = float(subtotal)

    if grand_total is None:
        tax_amount = subtotal * (tax_rate / 100) if tax_rate > 0 else 0
        grand_total = subtotal - discount + tax_amount
    else:
        grand_total = float(grand_total)
        tax_amount = subtotal * (tax_rate / 100) if tax_rate > 0 else 0

    totals_rows = [[
        Paragraph("Subtotal", cell(9, 12, _RECEIPT_INK, TA_RIGHT)),
        Paragraph(_receipt_money(subtotal, currency), cell(9, 12, _RECEIPT_INK, TA_RIGHT)),
    ]]
    if discount and discount != 0:
        totals_rows.append([
            Paragraph("Discount", cell(8.5, 12, _RECEIPT_SUBTLE, TA_RIGHT)),
            Paragraph(f"-{_receipt_money(abs(discount), currency)}", cell(8.5, 12, _RECEIPT_SUBTLE, TA_RIGHT)),
        ])
    if tax_rate > 0:
        totals_rows.append([
            Paragraph(f"Tax ({tax_rate:g}%)", cell(8.5, 12, _RECEIPT_SUBTLE, TA_RIGHT)),
            Paragraph(_receipt_money(tax_amount, currency), cell(8.5, 12, _RECEIPT_SUBTLE, TA_RIGHT)),
        ])
    totals_rows.append([
        Paragraph("Grand Total", cell(11, 14, _RECEIPT_INK, TA_RIGHT, bold=True)),
        Paragraph(_receipt_money(grand_total, currency), cell(11, 14, _RECEIPT_INK, TA_RIGHT, bold=True)),
    ])
    totals_table = Table(totals_rows, colWidths=[60 * mm, 50 * mm])
    totals_style = [
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LINEABOVE", (0, 0), (-1, 0), 0.5, _RECEIPT_LINE),
        ("LINEABOVE", (0, -1), (-1, -1), 0.8, _RECEIPT_LINE),
        ("TOPPADDING", (0, -1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 6),
    ]
    totals_table.setStyle(TableStyle(totals_style))
    totals_wrap = Table([[Spacer(1, 1), totals_table]], colWidths=[70 * mm, 110 * mm])
    totals_wrap.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "BOTTOM"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(KeepTogether([totals_wrap]))
    story.append(Spacer(1, 6 * mm))

    # ── 5) Sections ──────────────────────────────────────────────────────
    sections = []
    if data.get("notes"):
        sections.append(("NOTES", str(data["notes"])))
    if data.get("terms"):
        sections.append(("TERMS & CONDITIONS", str(data["terms"])))
    if data.get("payment_terms"):
        sections.append(("PAYMENT TERMS", str(data["payment_terms"])))
    if data.get("delivery"):
        sections.append(("ESTIMATED DELIVERY", str(data["delivery"])))
    if sections:
        story.append(HRFlowable(width="100%", thickness=0.5, color=_RECEIPT_LINE, spaceBefore=0, spaceAfter=0))
        story.append(Spacer(1, 5 * mm))
        for i, (heading, content) in enumerate(sections):
            if i:
                story.append(Spacer(1, 4 * mm))
            story.append(_q_section_title(heading))
            story.append(Spacer(1, 2 * mm))
            story.append(Paragraph(content, ParagraphStyle(
                "qbody", fontName="Helvetica", fontSize=8.5, leading=13,
                textColor=_RECEIPT_SUBTLE, wordWrap="CJK")))
        story.append(Spacer(1, 4 * mm))

    # ── Acceptance ───────────────────────────────────────────────────────
    if data.get("terms"):
        story.append(HRFlowable(width="100%", thickness=0.4, color=_RECEIPT_LINE, spaceBefore=0, spaceAfter=0))
        story.append(Spacer(1, 5 * mm))
        story.append(_q_section_title("ACCEPTANCE"))
        story.append(Spacer(1, 3 * mm))
        acc_rows = [[Paragraph(line, ParagraphStyle(
            "qacc", fontName="Helvetica", fontSize=8.5, leading=11,
            textColor=_RECEIPT_SUBTLE, wordWrap="CJK")) for line in (
            "Accepted By: ______________________",
            "Date: ____________________________")]]
        acc_table = Table(acc_rows, colWidths=[60 * mm, 60 * mm])
        acc_table.setStyle(TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(KeepTogether([acc_table]))
        story.append(Spacer(1, 6 * mm))

    doc.build(story, canvasmaker=_QuoteCanvas)
    return buf.getvalue()


def invoice_pdf(data):
    """Generate a SERPHAWK-minimal invoice PDF (A4 portrait).

    ``data`` is a dict with keys:
        invoice_number, client_name, currency (default "$"),
        amount, tax, total, status, due_date, notes,
        line_items: [ { description, amount, provider } ]
    """
    from datetime import datetime as _dt

    company = "SERPHAWK"
    currency = str(data.get("currency") or "$")
    subtitle = "Invoice"
    inv_num = data.get("invoice_number") or str(data.get("id") or "")
    created = data.get("created_at") or ""
    if hasattr(created, "strftime"):
        created = _spanish_datetime(created)
    elif isinstance(created, str) and created:
        pass
    else:
        created = _spanish_datetime(_dt.now())

    line_items = data.get("line_items") or []

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=14 * mm, bottomMargin=16 * mm,
        title=f"{company} — Invoice {inv_num}",
        author=company,
    )

    def cell(fs=9, ls=12, color=_RECEIPT_INK, align=TA_LEFT, bold=False, wrap=True):
        return ParagraphStyle(
            "ip", fontName="Helvetica-Bold" if bold else "Helvetica",
            fontSize=fs, leading=ls, textColor=color, alignment=align,
            spaceBefore=0, spaceAfter=0, wordWrap="CJK" if wrap else None,
        )

    story = []

    # ── Header ───────────────────────────────────────────────────────────
    meta_lines = []
    if inv_num:
        meta_lines.append(("Invoice:", inv_num))
    if created:
        meta_lines.append(("Date:", str(created)))
    if data.get("due_date"):
        meta_lines.append(("Due:", data["due_date"]))
    if data.get("client_name"):
        meta_lines.append(("Bill To:", data["client_name"]))
    story += _serphawk_header(company, meta_lines if meta_lines else None, subtitle=subtitle)

    # ── Client / status info ─────────────────────────────────────────────
    info_rows = []
    if data.get("client_name"):
        info_rows.append([
            Paragraph("<b>Bill To:</b>", cell(9, 12, _RECEIPT_INK, bold=True)),
            Paragraph(data["client_name"], cell(9, 12, _RECEIPT_INK)),
        ])
    if data.get("status"):
        info_rows.append([
            Paragraph("<b>Status:</b>", cell(9, 12, _RECEIPT_INK, bold=True)),
            Paragraph(data["status"], cell(9, 12, _RECEIPT_INK)),
        ])
    if data.get("due_date"):
        info_rows.append([
            Paragraph("<b>Due Date:</b>", cell(9, 12, _RECEIPT_INK, bold=True)),
            Paragraph(data["due_date"], cell(9, 12, _RECEIPT_INK)),
        ])
    if info_rows:
        info_table = Table(info_rows, colWidths=[30 * mm, 150 * mm])
        info_table.setStyle(TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 1.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 5 * mm))

    # ── Line items table ─────────────────────────────────────────────────
    headers = ["#", "Description", "Provider", "Amount"]
    col_w = [12 * mm, 112 * mm, 28 * mm, 28 * mm]
    data_rows = [
        [Paragraph(h, cell(7.5, 10, _RECEIPT_SUBTLE, TA_LEFT, bold=True)) for h in headers]
    ]
    for idx, li in enumerate(line_items, 1):
        amt = float(li.get("amount", 0))
        prov = li.get("provider", "")
        desc = li.get("description", "")
        data_rows.append([
            Paragraph(str(idx), cell(8.5, 11, _RECEIPT_FAINT, TA_CENTER)),
            Paragraph(str(desc), cell(9, 12, _RECEIPT_INK, TA_LEFT)),
            Paragraph(str(prov), cell(8.5, 11, _RECEIPT_SUBTLE, TA_LEFT)),
            Paragraph(f"{currency}{amt:.2f}", cell(8.5, 11, _RECEIPT_INK, TA_RIGHT)),
        ])

    if not line_items:
        data_rows.append([
            Paragraph("—", cell(9, 12, _RECEIPT_FAINT, TA_CENTER)),
            Paragraph("No line items", cell(9, 12, _RECEIPT_FAINT)),
            Paragraph("—", cell(9, 12, _RECEIPT_FAINT)),
            Paragraph("—", cell(9, 12, _RECEIPT_FAINT)),
        ])

    item_style = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 2),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING", (0, 0), (-1, 0), 0),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 4),
        ("TOPPADDING", (0, 1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, 0), 0.6, _RECEIPT_LINE),
    ]
    for idx in range(1, len(data_rows)):
        item_style.append(("LINEBELOW", (0, idx), (-1, idx), 0.5, _RECEIPT_LINE))

    items_table = Table(data_rows, colWidths=col_w, repeatRows=1)
    items_table.setStyle(TableStyle(item_style))
    story.append(items_table)
    story.append(Spacer(1, 6 * mm))

    # ── Totals ───────────────────────────────────────────────────────────
    amount = float(data.get("amount") or 0)
    tax = float(data.get("tax") or 0)
    total = float(data.get("total") or (amount + tax))

    totals_rows = [
        ["", Paragraph("Subtotal", cell(9, 12, _RECEIPT_INK, TA_RIGHT)),
         Paragraph(_receipt_money(amount, currency), cell(9, 12, _RECEIPT_INK, TA_RIGHT))],
    ]
    if tax > 0:
        totals_rows.append([
            "", Paragraph("Tax", cell(9, 12, _RECEIPT_SUBTLE, TA_RIGHT)),
            Paragraph(_receipt_money(tax, currency), cell(9, 12, _RECEIPT_SUBTLE, TA_RIGHT)),
        ])
    totals_rows.append([
        "", Paragraph("Total", cell(11, 14, _RECEIPT_INK, TA_RIGHT, bold=True)),
        Paragraph(_receipt_money(total, currency), cell(11, 14, _RECEIPT_INK, TA_RIGHT, bold=True)),
    ])

    totals_table = Table(totals_rows, colWidths=[92 * mm, 40 * mm, 48 * mm])
    totals_style = [
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, 0), 0.6, _RECEIPT_LINE),
        ("LINEBELOW", (0, -1), (-1, -1), 0.6, _RECEIPT_LINE),
        ("TOPPADDING", (0, -1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 5),
    ]
    totals_table.setStyle(TableStyle(totals_style))
    story.append(KeepTogether([totals_table]))

    # ── Notes ────────────────────────────────────────────────────────────
    notes = data.get("notes") or ""
    if notes:
        story.append(Spacer(1, 8 * mm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=_RECEIPT_LINE))
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("Notes", cell(9, 12, _RECEIPT_INK, bold=True)))
        story.append(Spacer(1, 2 * mm))
        story.append(Paragraph(notes, cell(8.5, 11, _RECEIPT_SUBTLE)))

    # ── Footer (later pages only) ────────────────────────────────────────
    def _i_footer(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(_RECEIPT_FAINT)
        canvas.drawRightString(A4[0] - 15 * mm, 9 * mm, f"Invoice {inv_num} · Página {_doc.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=lambda c, d: None, onLaterPages=_i_footer)
    return buf.getvalue()